a=[10,20,30,40] #[0]=10,[1]=20,[3]=30,[4]=40.
a[0]
o/p=10
a[6]  #6 index is not there in input of a
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    a[6]
IndexError: list index out of range
a[3]
o/p=40
a[2]
o/p=30

